### ISSUE TITLE
It's weird that futures appears (and that it appears as incompatible with Python 3)

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [chhantyal/py3readiness#56]
[`futures`](https://pypi.org/project/futures/) is a backport of a Python 3 standard library module, so it's a bit of a special case, but its latest version says "It should not be installed on Python 3, although there should be no harm in doing so, as the standard library takes precedence over third party libraries.". Doesn't that text suggest that it shouldn't appear white in the compatibility list?

Somewhat separately: given that `futures` is useful on 2.7 only, should it particularly matter whether or not it is compatible with Python 3? Should it even appear in the list at all, whether in green or in white?

Does the text "[Green packages support Python 3 (or has drop in replacement package which supports Python 3)](http://py3readiness.org/)" play any role for `futures`, given that its drop-in replacement not only exists, but is part of Python 3 itself?

**Comment by hugovk** [comment]
This sites uses caniusepython3 to decide if something is ready:
 
```console
$ caniusepython3 --projects futures
Finding and checking dependencies ...

You need 1 project to transition to Python 3.
Of that 1 project, 1 has no direct dependencies blocking its transition:

  futures
```

---

https://github.com/brettcannon/caniusepython3#how-do-you-tell-if-a-project-has-been-ported-to-python-3 says:

> # How do you tell if a project has been ported to Python 3?
> 
> On [PyPI](https://pypi.python.org/) each project can specify various
[trove classifiers](https://pypi.python.org/pypi?%3Aaction=list_classifiers)
(typically in a project's `setup.py` through a [`classifier`](https://docs.python.org/3/distutils/setupscript.html#additional-meta-data)
argument to `setup()`).
> There are various classifiers related to what version of Python a project can
run on. E.g.:
> 
>     Programming Language :: Python :: 3
>     Programming Language :: Python :: 3.0
>     Programming Language :: Python :: 3.1
>     Programming Language :: Python :: 3.2
>     Programming Language :: Python :: 3.3
>     Programming Language :: Python :: 3.4
>     Programming Language :: Python :: 3.5
>     Programming Language :: Python :: 3.6
> 
> As long as a trove classifier for some version of Python 3 is specified then the
project is considered to support Python 3 (project owners: it is preferred you
**at least** specify `Programming Language :: Python :: 3` as that is how you
end up listed on the [Python 3 Packages list on PyPI](https://pypi.python.org/pypi?%3Aaction=packages_rss);
you can represent Python 2 support with `Programming Language :: Python`).  Note
that Python 3.0 through 3.3 have reached their [End Of Life](https://docs.python.org/devguide/index.html#branchstatus).
> 
> The other way is through a [manual override](https://github.com/brettcannon/caniusepython3/blob/master/caniusepython3/overrides.json) in
`caniusepython3` itself. Projects ends up on this list because:
> 
> * They are now part of [Python's standard library](http://docs.python.org/3/py-modindex.html) in some release of Python 3
> * Their Python 3 port is under a different name
> * They are missing a Python 3 trove classifier but have actually been ported
> 
> If any of these various requirements are met, then a project is considered to
support Python 3 and thus will be added to the manual overrides list. You can
see the list of overrides when you use caniusepython3's CLI with verbose output
turned on.

---

Futures declares itself as only compatible for Python 2:
```
"Programming Language :: Python :: 2.6",
"Programming Language :: Python :: 2.7",
"Programming Language :: Python :: 2 :: Only"
```
https://pypi.org/pypi/futures/json

But it sounds like it meets caniusepython3's third requirement for going on the override list. Please file a PR or issue over there: https://github.com/brettcannon/caniusepython3#what-if-i-know-of-a-project-that-should-be-added-to-the-overrides-file

**Comment by anarcat** [comment]
futures *is* in the overrides file in caniuse: https://github.com/brettcannon/caniusepython3/commit/fbf6360a5e5c487984605d543f0623b9a7058bfb it's been there for years. either the version running here is very old or something fishy is going on.

**Comment by anarcat** [comment]
a similar issue occurs with beautifulsoup, FWIW.

**Comment by nathanielmanistaatgoogle** [comment]
@brettcannon: what was stale about `futures` in "[Clear out stale overrides](https://github.com/brettcannon/caniusepython3/commit/71ae84ad13b17d58569816f465cda449e2e128d2#diff-2a920615b7b2e134ffa4173d8ab21518)?

**Comment by brettcannon** [comment]
They probably had a trove classifier for Python 3 that they subsequently dropped.

**Comment by hugovk** [comment]
Here's a PR to re-add futures to the overrides: https://github.com/brettcannon/caniusepython3/pull/187.

**Comment by hugovk** [comment]
https://github.com/brettcannon/caniusepython3/pull/187 is now merged and futures is no longer a Python 3 blocker:

```
$ caniusepython3 --projects futures
Finding and checking dependencies ...

🎉  You have 0 projects blocking you from using Python 3!
```

---

Here's a static build of py3readiness and futures is now green:

https://hugovk.github.io/py3readiness/

![image](https://user-images.githubusercontent.com/1324225/45473474-d8079b80-b73f-11e8-9424-85b112024f9e.png)

...

![image](https://user-images.githubusercontent.com/1324225/45473489-e0f86d00-b73f-11e8-8987-4c2fe175a3bf.png)

---

@nathanielmanistaatgoogle This issue can now be closed, thanks for raising it!

**Comment by nathanielmanistaatgoogle** [comment]
Woohoo! Thanks much!

**Comment by anarcat** [comment]
whoohoo! this means all 120 (120? why not 100! :) most popular packages in PyPI are now green! congratulations on everyone on making this happen!

**Comment by hugovk** [comment]
Both python-augeas and pandocfilters support Python 3, the classifiers will be in their next releases. 

https://github.com/hercules-team/python-augeas/commits/master/setup.py

https://github.com/jgm/pandocfilters/commits/master/setup.py
